### ISSUE TITLE
Crear pagina de testimonials

### ISSUE THREAD

**Issue by misscs** [cosola-macile/macile.org#93]
### Vision

What do we want out of this feature?

### Current State

What is currently implemented (or not implemented)?

### Scope

- [x] Añadir un modulo testimonials
- [x] Añadir `index.js`

### Anti-Vision

What is out of scope or goes against the original intention?

**Comment by misscs** [comment]
Es `modules/content_panel.css`

```css
.section-hero {
  display: flex;
  align-items: center;
  justify-content: center;
  position: relative;
  height: 40vh;
  overflow: hidden;
  background: lightgrey;
  padding: 10rem 5rem;
}

.hero-image {
  position: absolute;
  left: 0;
  top: 0;
}

.hero-text {
  font-size: 16px;
  position: relative;
  z-index: 1;
  text-align: center;
  color: #fff;
}

.hero-headline {
  font-size: 28px;
  margin-bottom: 10px;
}

.hero-byline {
  font-weight: bold;
  font-size: 20px;
}

```


Es de `modules/content_panel.macros.html`

```jinja
 {% macro content_panel(data) %}
  <div class="content-panel">
    {% if data.image %}
      <figure class="panel-figure">
        <img class="panel-img" src="{{ data.image }}" alt="{{ data.image_alt }}">
      </figure>
    {% endif %}
    <div class="panel-information">
      {% if data.href_path %}
       <h2><a href="{{ data.href_path }}">{{ data.title }}</a></h2>
      {% endif %}
      <p>{{ data.description }}</p>
    </div>
  </div>
{% endmacro %} 
```
